# Port of HTTP(S) proxy server on the local end
port: 7890

# Port of SOCKS5 proxy server on the local end
socks-port: 7891

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S) and SOCKS4(A)/SOCKS5 server on the same port
# mixed-port: 7890

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: true

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
bind-address: '*'

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: info

# When set to false, resolver won't translate hostnames to IPv6 addresses
# ipv6: true

# RESTful web API listening address
external-controller: 127.0.0.1:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
# external-ui: folder

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# secret: ""

# Outbound interface name
# interface-name: en0

# fwmark on Linux only
# routing-mark: 6666

# Static hosts for DNS server and connection establishment (like /etc/hosts)
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
# hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'

# profile:
  # Store the `select` results in $HOME/.config/clash/.cache
  # set false If you don't want this behavior
  # when two different configurations have groups with the same name, the selected values are shared
  # store-selected: false

  # persistence fakeip
  # store-fake-ip: true

# DNS server settings
# This section is optional. When not present, the DNS server will be disabled.
# dns:
#   enable: false
#   listen: 0.0.0.0:53
  # ipv6: false # when the false, response to AAAA questions will be empty

  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  # default-nameserver:
  #   - 114.114.114.114
  #   - 8.8.8.8
  # enhanced-mode: fake-ip # or redir-host (not recommended)
  # fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  # use-hosts: true # lookup hosts and return IP record
  
  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com
  
  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  # nameserver:
  #   - 114.114.114.114 # default value
  #   - 8.8.8.8 # default value
  #   - tls://dns.rubyfish.cn:853 # DNS over TLS
  #   - https://1.1.1.1/dns-query # DNS over HTTPS
  #   - dhcp://en0 # dns from dhcp
    # - '8.8.8.8#en0'

  # When `fallback` is present, the DNS server will send concurrent requests
  # to the servers in this section along with servers in `nameservers`.
  # The answers from fallback servers are used when the GEOIP country
  # is not `CN`.
  # fallback:
  #   - tcp://1.1.1.1
  #   - 'tcp://1.1.1.1#en0'

  # If IP addresses resolved with servers in `nameservers` are in the specified
  # subnets below, they are considered invalid and results from `fallback`
  # servers are used instead.
  #
  # IP address resolved with servers in `nameserver` is used when
  # `fallback-filter.geoip` is true and when GEOIP of the IP address is `CN`.
  #
  # If `fallback-filter.geoip` is false, results from `nameserver` nameservers
  # are always used if not match `fallback-filter.ipcidr`.
  #
  # This is a countermeasure against DNS pollution attacks.
  # fallback-filter:
  #   geoip: true
  #   geoip-code: CN
  #   ipcidr:
  #     - 240.0.0.0/4
  #   domain:
  #     - '+.google.com'
  #     - '+.facebook.com'
  #     - '+.youtube.com'
  
  # Lookup domains via specific nameservers
  # nameserver-policy:
  #   'www.baidu.com': '114.114.114.114'
  #   '+.internal.crop.com': '10.0.0.1'

proxies:
  # vmess
  # cipher support auto/aes-128-gcm/chacha20-poly1305/none
  # - name: "vmess"
  #   type: vmess
  #   server: server
  #   port: 443
  #   uuid: uuid
  #   alterId: 32
  #   cipher: auto
    # udp: true
    # tls: true
    # skip-cert-verify: true
    # servername: example.com # priority over wss host
    # network: ws
    # ws-opts:
    #   path: /path
    #   headers:
    #     Host: v2ray.com
    #   max-early-data: 2048
    #   early-data-header-name: Sec-WebSocket-Protocol

  - name: trojan-grpc
    server: server
    port: 443
    type: trojan
    password: "example"
    network: grpc
    sni: example.com
    # skip-cert-verify: true
    udp: true
    grpc-opts:
      grpc-service-name: "example"

proxy-groups:
  - name: "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
    type: select
    proxies:
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
    #  - "ğŸ‡¸ğŸ‡¬ ç‹®åŸ"

  - name: "ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"
    type: select
    proxies:
      - ğŸ‡¯ğŸ‡µ CF grpc
      - ğŸ‡¯ğŸ‡µ CF ws
      - ğŸ‡¯ğŸ‡µ ç›´è¿ grpc
      - ğŸ‡¯ğŸ‡µ ç›´è¿ ws
      - ğŸ‡­ğŸ‡° CF grpc
      - ğŸ‡­ğŸ‡° CF ws
      - ğŸ‡­ğŸ‡° ç›´è¿ grpc
      - ğŸ‡­ğŸ‡° ç›´è¿ ws

  - name: "ğŸ“º å“”å“©å“”å“©"
    type: select
    proxies:
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯

  - name: "â“‚ï¸ å¾®è½¯"
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT

  - name: "ğŸ è‹¹æœ"
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢

  - name: "ğŸ® CNCDN"
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢

  - name: "ğŸ” Ehentai"
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT

  - name: "ğŸŸ æ¼ç½‘ä¹‹é±¼"
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬
      - ğŸ‡­ğŸ‡° é¦™æ¸¯
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT

  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° CF grpc
      - ğŸ‡­ğŸ‡° CF ws
      - ğŸ‡­ğŸ‡° ç›´è¿ grpc
      - ğŸ‡­ğŸ‡° ç›´è¿ ws

  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    type: select
    proxies:
      - ğŸ‡¯ğŸ‡µ CF grpc
      - ğŸ‡¯ğŸ‡µ CF ws
      - ğŸ‡¯ğŸ‡µ ç›´è¿ grpc
      - ğŸ‡¯ğŸ‡µ ç›´è¿ ws

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

  FCMdomain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/kagurainroy/Clash_Rules/main/RuleProviders/FCMdomain.yaml"
    path: ./ruleset/FCMdomain.yaml
    interval: 360000
  
  FCMip:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/kagurainroy/Clash_Rules/main/RuleProviders/FCMip.yaml"
    path: ./ruleset/FCMip.yaml
    interval: 360000

  bilibili:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/kagurainroy/Clash_Rules/main/RuleProviders/bilibili.yaml"
    path: ./ruleset/bilibili.yaml
    interval: 360000

  bilibiliHMTdomain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/kagurainroy/Clash_Rules/main/RuleProviders/bilibiliHMTdomain.yaml"
    path: ./ruleset/bilibiliHMTdomain.yaml
    interval: 360000

  bilibiliHMTip:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/kagurainroy/Clash_Rules/main/RuleProviders/bilibiliHMTip.yaml"
    path: ./ruleset/bilibiliHMTip.yaml
    interval: 360000

  eh:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/kagurainroy/Clash_Rules/main/RuleProviders/eh.yaml"
    path: ./ruleset/eh.yaml
    interval: 360000
    
  epic:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/kagurainroy/Clash_Rules/main/RuleProviders/epic.yaml"
    path: ./ruleset/epic.yaml
    interval: 360000

  microsoft:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/kagurainroy/Clash_Rules/main/RuleProviders/microsoft.yaml"
    path: ./ruleset/microsoft.yaml
    interval: 360000

  onedrive:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/kagurainroy/Clash_Rules/main/RuleProviders/onedrive.yaml"
    path: ./ruleset/onedrive.yaml
    interval: 360000

  steamdomain:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/kagurainroy/Clash_Rules/main/RuleProviders/steamdomain.yaml"
    path: ./ruleset/steamdomain.yaml
    interval: 360000

  steamip:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/kagurainroy/Clash_Rules/main/RuleProviders/steamip.yaml"
    path: ./ruleset/steamip.yaml
    interval: 360000  


rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,FCMdomain,DIRECT
  - RULE-SET,bilibili,ğŸ“º å“”å“©å“”å“©
  - RULE-SET,bilibiliHMTdomain,ğŸ“º å“”å“©å“”å“©
  - RULE-SET,eh,ğŸ” Ehentai
  - RULE-SET,epic,ğŸ® CNCDN
  - RULE-SET,steamdomain,ğŸ® CNCDN
  - RULE-SET,icloud,ğŸ è‹¹æœ
  - RULE-SET,apple,ğŸ è‹¹æœ
  - RULE-SET,microsoft,â“‚ï¸ å¾®è½¯
  - RULE-SET,onedrive,â“‚ï¸ å¾®è½¯
  - RULE-SET,google,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,proxy,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT,no-resolve
  - RULE-SET,FCMip,DIRECT,no-resolve
  - RULE-SET,bilibiliHMTip,ğŸ“º å“”å“©å“”å“©,no-resolve
  - RULE-SET,steamip,ğŸ® CNCDN,no-resolve
  - RULE-SET,telegramcidr,ğŸš€ èŠ‚ç‚¹é€‰æ‹©,no-resolve  
  - RULE-SET,cncidr,DIRECT,no-resolve
  - GEOIP,LAN,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
